name: branches

on:
  push:
    branches: ['!master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache emulator
      uses: actions/cache@v4
      id: cache-deps-fb
      with:
        path: ~/.cache/firebase/emulators
        key: ${{ runner.os }}-fb-${{ hashFiles('firebase.json') }}
        restore-keys: |
              ${{ runner.os }}-fb-

    - name: Run tests
      env: 
        FIRE: ${{ secrets.FIRE }}
        VISION_API: ${{ secrets.VISION_API }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        NPM_CONFIG_PREFIX: ~/.npm-global
      run: |
        mkdir -p ~/.npm-global
        npm config set prefix '~/.npm-global'
        export PATH=~/.npm-global/bin:$PATH
        source ~/.profile
        npm install -g firebase-tools@8.5.0
        bash ./ci.sh
