name: branches

on:
  push:
    branches: ['!master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      env: 
        FIRE: ${{ secrets.FIRE }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        NPM_CONFIG_PREFIX: ~/.npm-global
        _JAVA_OPTIONS: -Xmx6g
      run: |
        mkdir -p ~/.npm-global
        npm config set prefix '~/.npm-global'
        export PATH=~/.npm-global/bin:$PATH
        source ~/.profile
        npm install -g firebase-tools@8.5.0
        bash ./ci.sh
        bash ./graaltest.sh
