name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      env: 
        FIRE: ${{ secrets.FIRE }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        npm install -g firebase-tools@8.5.0
        bash ./ci.sh
        bash <(curl -s https://codecov.io/bash)