name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      env: 
        FIRE: ${{ secrets.FIRE }}
        FIREBASE_API: ${{ secrets.API_KEY }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIRE }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        lein cloverage --codecov
        bash <(curl -s https://codecov.io/bash)
