name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build env
      run: |
        docker-compose up -d
        sleep 20
  build:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      env: 
        FIRE: ${{ secrets.FIRE }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        lein cloverage --codecov
        bash <(curl -s https://codecov.io/bash)
    - name: Clean env
      run: docker-compose down